name: Sync Repository Action
on:
  push:
  schedule:
    # 每周一0:00
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-dr/sync-repo-to-gitee@master
      env:
          # 在 Settings->Secrets 配置 GITEE_KEY
          SSH_KEY: ${{ secrets.GITEE_KEY }}
      with:
          # GitHub存储库的SSH URL.
          github-repo: git@github.com:xiaohai2271/blog-backEnd.git
          # Gitee存储库的SSH URL.
          gitee-repo: git@gitee.com:xiaohai2271/blog-backEnd.git
